### ISSUE TITLE
hard_wrap not working?

### ISSUE THREAD

**Issue by ZaneCEO** [KnpLabs/KnpMarkdownBundle#104]
Hi! I've a markdown input like this:

````
word1
word2
````

What I need to generate is this:

````
<p>word1<br>
word2</p>
````

So I set the `hard_wrap` like this:

````
knp_markdown:
  parser:
    service: markdown.parser.max

  # https://github.com/chobie/php-sundown/blob/master/docs/ExtensionsAndRenderFlags.md
  sundown:
    extensions:
      autolink: true
      space_after_headers: false
    render_flags:
      hard_wrap: true
````

The configuration is read as expected:

````
Current configuration for "KnpMarkdownBundle"
=============================================

knp_markdown:
    parser:
        service: markdown.parser.max
    sundown:
        extensions:
            autolink: true
            space_after_headers: false
            fenced_code_blocks: false
            no_intra_emphasis: false
            tables: false
            strikethrough: false
            lax_html_blocks: false
            superscript: false
        render_flags:
            hard_wrap: true
            filter_html: false
            no_images: false
            no_links: false
            no_styles: false
            safe_links_only: false
            with_toc_data: false
            xhtml: false
````

Unfortunately, **hard_wrap doesn't work**. What I get is this:

````
<p>word1
word2</p>
````

I'm with Symfony 4.4.8, PHP 7.3, KnpMarkdownBundle 1.8.1.

I'm pretty sure this is just me missing something obvious here.

Thanks!
