### ISSUE TITLE
Double underscores are not being parsed as strong text when extra whitespace exists

### ISSUE THREAD

**Issue by sepehr** [KnpLabs/KnpMarkdownBundle#95]
​Configuration:

```yaml
knp_markdown:
    parser:
        service: markdown.parser.max
```

Not sure how markdown specification works regarding this, but if the surrounded text has an extra whitespace it won't be rendered as strong text.

Please feel free to close this if it's not an issue in this bundle.
